### ISSUE TITLE
Remove Ketchup

### ISSUE THREAD

**Issue by proyb6** [postlight/awesome-cms#123]
Ketchup hasn't been updated for years, the remaining inactive CMS could be removed?

**Comment by fdsimms** [comment]
hey @proyb6! thanks for opening this issue. we chatted about it a little, and for now we're going to keep older CMSes around for posterity's sake and so developers have more options to look at, especially in a category like Go where we only have 2 listed. we do show how long it's been since a repo has had a commit, so we're hoping that helps guide devs to be more careful when deciding whether to use those CMSes. if Ketchup is completely broken and unusable in its current state, that's a different story, but it doesn't seem like that's necessarily the case. please let me know if i'm wrong on that, and we can reopen this. thanks again!
